-- Seed data for testing Rentals and Services

-- 1. Create a test merchant (if not exists)
INSERT INTO merchants (id, name, email, subscription_tier)
VALUES (999, 'Test Merchant', 'test@bouteek.shop', 'starter')
ON CONFLICT (id) DO NOTHING;

-- 2. Create a test storefront
INSERT INTO storefronts (merchant_id, name, slug, custom_domain_status)
VALUES (999, 'Test Store', 'test-store', 'verified')
ON CONFLICT (slug) DO NOTHING;

-- 3. Create a RENTAL listing
INSERT INTO listings (
    merchant_id, 
    title, 
    description, 
    price, 
    base_price, 
    currency, 
    image_urls, 
    module_type, 
    metadata
)
VALUES (
    999,
    'Luxury Beach House',
    'Beautiful beach house for weekend getaways.',
    50000, -- 50,000 XOF per day
    50000,
    'XOF',
    ARRAY['https://images.unsplash.com/photo-1499793983690-e29da59ef1c2'],
    'rental',
    '{
        "rental_unit": "night",
        "deposit_amount": 25000,
        "require_id_verification": true
    }'
);

-- 4. Create a SERVICE listing
INSERT INTO listings (
    merchant_id, 
    title, 
    description, 
    price, 
    base_price, 
    currency, 
    image_urls, 
    module_type, 
    metadata
)
VALUES (
    999,
    'Spa Treatment',
    'Relaxing full body massage.',
    15000,
    15000,
    'XOF',
    ARRAY['https://images.unsplash.com/photo-1544161515-4ab6ce6db874'],
    'service',
    '{
        "duration_minutes": 60,
        "allow_specialist_selection": true
    }'
);

-- 5. Add available slots (for service) - Requires inventory table knowledge, assuming standard structure
-- INSERT INTO inventory_slots ... (Skipped as schema varies, usually generated by logic)
